### ISSUE TITLE
Recomendacion para futuros commits

### ISSUE THREAD

**Issue by HopeAero** [adiazt01/chat-app#1]
![image](https://github.com/user-attachments/assets/72fa3cb9-5d89-4558-b1fb-e6f134822244)

teniendo en cuenta que tienes 2 KEYS en el .env y ademas tambien PostgreSQL Connection String te full recomiendo usar .gitignore si no quieres que las personas tengan acceso a las llaves privadas e cualquier informacion que coloques ahi en el .env

https://www.freecodecamp.org/espanol/news/gitignore-explicado-que-es-y-como-agregar-a-tu-repositorio/

**Comment by adiazt01** [comment]
Si la verdad se me habia escapado agregar los .env en el .gitignore, muchas gracias!
